config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  get '/dashboard', to: 'users#show'
  resources :songs, only: [:show]
  resources :stravas, only: [:create]

  get 'auth/strava/callback', to: 'login#create'
  get 'auth/spotify/callback', to: 'spotify#create'
  get 'spotify/songs', to: 'spotify#index'
  post '/playlist', to: 'playlist#create'

  post 'hooks/strava', to: 'hooks#strava'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_songs
  has_many :songs, through: :user_songs
  has_many :activities

  def top_songs(limit)
    songs
    .select("songs.*, MAX(user_songs.played_at) AS last_played_at, AVG(user_songs.power_ranking) AS avg_power_ranking, COUNT(user_songs.played_at) AS play_count")
      .where("power_ranking > 0")
      .group("songs.id")
      .order("avg_power_ranking DESC")
      .limit(limit)
  end

  def last_activity_id
    activities
      .order(strava_id: :DESC)
      .pluck(:strava_id)
      .first
  end

  def play_count(song)
    user_songs
      .where(song_id: song.id)
      .size
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# controller for user actions and dashboard
class UsersController < ApplicationController
  def show
    render locals: {
      facade: DashboardShowFacade.new(current_user)
    }
  end
end

app/views/users/show.html.erb
<nav class="navbar navbar-dark bg-dark fixed-top">
  <a href="<%= dashboard_path %>">
    <img src="<%= image_url('fasttracks-logo.png') %>">
  </a>
  <h1 class="nav-title">FastTracks</h1>
</nav>
<section class="container main-content">

  <section class="row">
    <div class="col-lg-12">
      <section class="py-md-3">
        <h1> <%= facade.user_name %>, Welcome to FastTracks </h1>
      </section>
      <section>
        <% if current_user.spotify_token.nil? %>
          <p>Please <%= link_to "Connect to Spotify",	facade.build_link %>
          to get the full benefits of FastTracks.</p>
        <% end %>
      </section>

      <% if current_user.spotify_token %>
        <div class="row">
          <section class="col-lg-8 top-songs pt-md-5 pb-md-3">
            <h3>Top Songs</h3>
            <table class="table">
              <thead>
                <tr>
                  <th>Power Ranking</th>
                  <th>Title</th>
                  <th>Artist</th>
                  <th>Play Count</th>
                  <th>Last Played</th>
                </tr>
              </thead>
              <tbody>
                <% cache cache_key_for(current_user.user_songs, "top_songs-#{current_user.id}") do %>
                  <% facade.top_songs.each do |song| %>
                    <div class="song">
                      <tr>
                        <th scope="row" class="song-power-index"><%= (song.avg_power_ranking * 100).to_i %></th>
                        <td class="song-title"><a href="<%= song_path(song.id) %>"><%= song.title %></a></td>
                        <td class="song-artist"><%= song.artist %></td>
                        <td class="song-play-count"><%= song.play_count %></td>
                        <td class="song-last-played"><%= song.updated_at.strftime('%m/%d/%y') %></td>
                      </tr>
                    </div>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </section>

          <section class="col-lg-4 pt-md-5 pb-md-3">
            <% if facade.top_songs.length > 4 %>
              <section class="recommended-songs">
                <h4>Recommended Songs</h4>
                  <% cache("recommended-songs-#{current_user.id}", expires_in: 30.minutes) do %>
                    <% facade.recommended_songs.each do |song| %>
                      <div class="recommended-song">
                        <iframe class="d-inline-block recommended-iframe recommended" src="https://open.spotify.com/embed/track/<%= song.spotify_id %>" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                        <%= form_tag playlist_path(song_uris: song.spotify_uri), method: :post, class: "d-inline-block add-single-form" do %>
                          <%= submit_tag 'Add', class: "d-inline-block btn btn-success add-single-btn" %>
                        <% end %>
                      </div>
                    <% end %>
                    <%= form_tag playlist_path(song_uris: facade.spotify_song_uris), method: :post do %>
                      <%= submit_tag 'Add All', class: "btn btn-success w-100" %>
                    <% end %>
                  <% end %>
                <%= link_to "Refresh Recommended", dashboard_path, id: "refresh-recs", remote: true, :"data_api_params" => facade.recommended_api_url %>
              </section>
            <% end %>
          </section>
        </div>
      <% end %>
    </div>
  </section>
</section>